version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll_site
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --host 0.0.0.0 --port 4000 --watch
